import { useCallback, useEffect, useState } from "react";
import { Pause, Play, Plus, RefreshCw, Rocket, ShieldCheck, X } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select"; import { Textarea } from "@/components/ui/textarea";
type Mission={id:number;type:string;name:string;objective:string;hypothesis:string;status:string;holdoutPercentage:number;latestResult?:Record<string,unknown>|null};
const headers=(json=false)=>({Authorization:`Bearer ${localStorage.getItem("admin_token")||""}`,...(json?{"Content-Type":"application/json"}:{})});
export default function AdminMissionsPage(){const[items,setItems]=useState<Mission[]>([]);const[selected,setSelected]=useState<Mission|null>(null);const[open,setOpen]=useState(false);const[form,setForm]=useState({type:"ABANDONED_CART_RECOVERY",name:"",objective:"",hypothesis:"",holdout:"10",minimum:"0",itemAId:"",itemBId:"",bundlePrice:""});
const load=useCallback(async()=>{try{const r=await fetch("/api/v1/missions",{headers:headers()});if(!r.ok)throw new Error();setItems((await r.json()).items||[])}catch{toast.error("Could not load missions")}},[]);useEffect(()=>{void load()},[load]);
const detail=async(id:number)=>{const r=await fetch(`/api/v1/missions/${id}`,{headers:headers()});if(r.ok)setSelected(await r.json());else toast.error("Could not load mission")};
const create=async()=>{const action=form.type==="INTELLIGENT_BUNDLE"?"SHOW_CART_UPSELL":"SEND_EMAIL";const audience=form.type==="ABANDONED_CART_RECOVERY"?{minimumCartValueCents:Number(form.minimum)}:form.type==="LAPSED_CUSTOMER_WINBACK"?{minimumOrderCount:2}:{itemAId:Number(form.itemAId),itemBId:Number(form.itemBId),...(form.bundlePrice?{proposedBundlePriceCents:Number(form.bundlePrice)}:{})};const r=await fetch("/api/v1/missions",{method:"POST",headers:headers(true),body:JSON.stringify({type:form.type,name:form.name,objective:form.objective,hypothesis:form.hypothesis,holdoutPercentage:Number(form.holdout),audience,actions:[{type:action,sequence:1,config:{noAutomaticDiscount:true}}]})});if(!r.ok){toast.error("Mission could not be created");return}setOpen(false);toast.success("Mission created for approval");await load()};
const act=async(action:string)=>{if(!selected)return;const r=await fetch(`/api/v1/missions/${selected.id}/${action}`,{method:"POST",headers:headers()});if(!r.ok){toast.error("Mission action failed");return}toast.success(`Mission ${action} request accepted`);await detail(selected.id);await load()};
return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Rocket className="h-6 w-6"/>Revenue Missions</h1><p className="text-sm text-muted-foreground">Approved interventions measured against deterministic holdouts.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button><Button onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4"/>New mission</Button></div></div>{!items.length?<Card><CardContent className="py-12 text-center text-sm text-muted-foreground">No missions yet.</CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{items.map(m=><Card key={m.id} className="cursor-pointer" onClick={()=>void detail(m.id)}><CardHeader><div className="flex justify-between gap-3"><CardTitle className="text-base">{m.name}</CardTitle><Badge>{m.status}</Badge></div></CardHeader><CardContent><p className="text-sm text-muted-foreground">{m.objective}</p><div className="mt-3 flex gap-2"><Badge variant="outline">{m.type.replace(/_/g," ")}</Badge><Badge variant="secondary">{m.holdoutPercentage}% holdout</Badge></div></CardContent></Card>)}</div>}
<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Create revenue mission</DialogTitle></DialogHeader><div className="space-y-3"><Label>Type</Label><Select value={form.type} onValueChange={type=>setForm({...form,type})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["ABANDONED_CART_RECOVERY","INTELLIGENT_BUNDLE","LAPSED_CUSTOMER_WINBACK"].map(x=><SelectItem key={x} value={x}>{x.replace(/_/g," ")}</SelectItem>)}</SelectContent></Select><Label>Name</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Label>Objective</Label><Textarea value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}/><Label>Hypothesis</Label><Textarea value={form.hypothesis} onChange={e=>setForm({...form,hypothesis:e.target.value})}/><Label>Holdout percentage</Label><Input type="number" min="0" max="50" value={form.holdout} onChange={e=>setForm({...form,holdout:e.target.value})}/>{form.type==="ABANDONED_CART_RECOVERY"&&<><Label>Minimum cart value (cents)</Label><Input type="number" min="0" value={form.minimum} onChange={e=>setForm({...form,minimum:e.target.value})}/></>}{form.type==="INTELLIGENT_BUNDLE"&&<><Label>First menu item ID</Label><Input type="number" value={form.itemAId} onChange={e=>setForm({...form,itemAId:e.target.value})}/><Label>Second menu item ID</Label><Input type="number" value={form.itemBId} onChange={e=>setForm({...form,itemBId:e.target.value})}/><Label>Optional bundle display price (cents)</Label><Input type="number" value={form.bundlePrice} onChange={e=>setForm({...form,bundlePrice:e.target.value})}/></>}</div><DialogFooter><Button onClick={()=>void create()} disabled={form.name.length<3||form.objective.length<10||form.hypothesis.length<10||(form.type==="INTELLIGENT_BUNDLE"&&(!form.itemAId||!form.itemBId))}>Create</Button></DialogFooter></DialogContent></Dialog>
<Dialog open={Boolean(selected)} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="max-w-2xl">{selected&&<><DialogHeader><DialogTitle>{selected.name}</DialogTitle></DialogHeader><p className="text-sm">{selected.hypothesis}</p><div className="flex gap-2"><Badge>{selected.status}</Badge><Badge variant="outline">{selected.type.replace(/_/g," ")}</Badge></div>{selected.latestResult?<pre className="max-h-72 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(selected.latestResult,null,2)}</pre>:<p className="text-sm text-muted-foreground">No measured result yet.</p>}<DialogFooter>{selected.status==="NEEDS_APPROVAL"&&<Button onClick={()=>void act("approve")}><ShieldCheck className="mr-2 h-4 w-4"/>Approve</Button>}{["APPROVED","SCHEDULED","PAUSED"].includes(selected.status)&&<Button onClick={()=>void act("start")}><Play className="mr-2 h-4 w-4"/>Start</Button>}{selected.status==="RUNNING"&&<Button variant="outline" onClick={()=>void act("pause")}><Pause className="mr-2 h-4 w-4"/>Pause</Button>}<Button variant="secondary" onClick={()=>void act("evaluate")}>Evaluate</Button>{!["COMPLETED","CANCELLED"].includes(selected.status)&&<Button variant="destructive" onClick={()=>void act("cancel")}><X className="mr-2 h-4 w-4"/>Cancel</Button>}</DialogFooter></>}</DialogContent></Dialog></div>}
