import { useCallback, useEffect, useState } from "react";
import { FlaskConical, Pause, Play, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type Experiment = { id:number; type:string; name:string; hypothesis:string; placement:string; minimumSample:number; status:string; latestResult?: { result:string; sampleSize:number; metrics:unknown } | null };
const headers = (json=false) => ({ Authorization:`Bearer ${localStorage.getItem("admin_token") || ""}`, ...(json?{"Content-Type":"application/json"}:{}) });

export default function AdminExperimentsPage() {
  const [items,setItems]=useState<Experiment[]>([]); const [selected,setSelected]=useState<Experiment|null>(null); const [open,setOpen]=useState(false);
  const [form,setForm]=useState({name:"",hypothesis:"",type:"BUTTON_COPY",placement:"HOME_PROMO_COPY",control:"Order fresh favorites online.",treatment:"Try a fresh favorite today."});
  const load=useCallback(async()=>{try{const r=await fetch("/api/v1/experiments",{headers:headers()});if(!r.ok)throw new Error();setItems((await r.json()).items||[])}catch{toast.error("Could not load experiments")}},[]);
  useEffect(()=>{void load()},[load]);
  const detail=async(id:number)=>{const r=await fetch(`/api/v1/experiments/${id}`,{headers:headers()});if(r.ok)setSelected(await r.json());else toast.error("Could not load experiment")};
  const create=async()=>{const r=await fetch("/api/v1/experiments",{method:"POST",headers:headers(true),body:JSON.stringify({type:form.type,name:form.name,hypothesis:form.hypothesis,placement:form.placement,conflictKey:`${form.placement}:copy`,variants:[{key:"control",name:"Control",config:{text:form.control},weight:50,isControl:true},{key:"treatment",name:"Treatment",config:{text:form.treatment},weight:50,isControl:false}]})});if(!r.ok){toast.error("Experiment could not be created");return}setOpen(false);toast.success("Experiment created for approval");await load()};
  const act=async(action:string)=>{if(!selected)return;const r=await fetch(`/api/v1/experiments/${selected.id}/${action}`,{method:"POST",headers:headers()});if(!r.ok){toast.error("Experiment action failed");return}toast.success(`Experiment ${action} request accepted`);await detail(selected.id);await load()};
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><FlaskConical className="h-6 w-6"/>Experiments</h1><p className="text-sm text-muted-foreground">Sticky assignments, render-only exposure, margin guardrails and confidence intervals.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button><Button onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4"/>New experiment</Button></div></div>
    {!items.length?<Card><CardContent className="py-12 text-center text-sm text-muted-foreground">No experiments yet.</CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{items.map(item=><Card key={item.id} className="cursor-pointer" onClick={()=>void detail(item.id)}><CardHeader><div className="flex justify-between gap-3"><CardTitle className="text-base">{item.name}</CardTitle><Badge>{item.status}</Badge></div></CardHeader><CardContent><p className="text-sm text-muted-foreground">{item.hypothesis}</p><div className="mt-3 flex gap-2"><Badge variant="outline">{item.type}</Badge><Badge variant="secondary">min {item.minimumSample}/variant</Badge></div></CardContent></Card>)}</div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Create controlled experiment</DialogTitle></DialogHeader><div className="space-y-3"><Label>Name</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Label>Hypothesis</Label><Textarea value={form.hypothesis} onChange={e=>setForm({...form,hypothesis:e.target.value})}/><Label>Type</Label><Select value={form.type} onValueChange={type=>setForm({...form,type})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["BUTTON_COPY","PRODUCT_NAME","PRODUCT_DESCRIPTION","PRODUCT_IMAGE","PRODUCT_POSITION","UPSELL","MENU_LAYOUT"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Label>Placement</Label><Input value={form.placement} onChange={e=>setForm({...form,placement:e.target.value})}/><Label>Control text</Label><Input value={form.control} onChange={e=>setForm({...form,control:e.target.value})}/><Label>Treatment text</Label><Input value={form.treatment} onChange={e=>setForm({...form,treatment:e.target.value})}/></div><DialogFooter><Button onClick={()=>void create()} disabled={form.name.length<3||form.hypothesis.length<10}>Create</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(selected)} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="max-w-2xl">{selected&&<><DialogHeader><DialogTitle>{selected.name}</DialogTitle></DialogHeader><p className="text-sm">{selected.hypothesis}</p><div className="flex gap-2"><Badge>{selected.status}</Badge><Badge variant="outline">{selected.placement}</Badge></div>{selected.latestResult?<pre className="max-h-72 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(selected.latestResult,null,2)}</pre>:<p className="text-sm text-muted-foreground">No evaluation result yet.</p>}<DialogFooter>{selected.status==="NEEDS_APPROVAL"&&<Button onClick={()=>void act("approve")}><ShieldCheck className="mr-2 h-4 w-4"/>Approve</Button>}{["SCHEDULED","PAUSED"].includes(selected.status)&&<Button onClick={()=>void act("start")}><Play className="mr-2 h-4 w-4"/>Start</Button>}{selected.status==="RUNNING"&&<Button variant="outline" onClick={()=>void act("pause")}><Pause className="mr-2 h-4 w-4"/>Pause</Button>}<Button variant="secondary" onClick={()=>void act("evaluate")}>Evaluate</Button></DialogFooter></>}</DialogContent></Dialog>
  </div>;
}
